In [1]:
import numpy, scipy, matplotlib.pyplot as plt, pandas, librosa

[&larr; Back to Index](index.html)

# NumPy and SciPy

The quartet of NumPy, SciPy, Matplotlib, and IPython is a popular combination in the Python world. We will use each of these libraries in this workshop.

## Tutorial

[NumPy](http://www.numpy.org) is one of the most popular libraries for numerical computing in the world. It is used in several disciplines including image processing, finance, bioinformatics, and more.  This entire workshop is based upon NumPy and its derivatives.

If you are new to NumPy, follow this [NumPy Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial).

[SciPy](http://docs.scipy.org/doc/scipy/reference/) is a Python library for scientific computing which builds on top of NumPy. If NumPy is like the Matlab core, then SciPy is like the Matlab toolboxes. It includes support for linear algebra, sparse matrices, spatial data structions, statistics, and more.

While there is a [SciPy Tutorial](http://docs.scipy.org/doc/scipy/reference/tutorial/index.html), it isn't critical that you follow it for this workshop.

## Special Arrays

In [4]:
numpy.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
numpy.linspace(0, 5, 10, endpoint=False)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [6]:
numpy.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
numpy.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
numpy.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
scipy.randn(5) # random Gaussian, zero-mean unit-variance

array([-1.02657947, -0.08601024,  0.89422667, -0.85211968,  1.18388355])

In [10]:
scipy.randn(5,2)

array([[-0.27356177, -0.30700966],
       [ 1.7424435 ,  1.10891904],
       [ 1.91013557,  0.27803479],
       [-0.39188448, -0.83528691],
       [ 2.02775849, -0.07458126]])

## Slicing Arrays

In [11]:
x = numpy.arange(10)
x[2:4]

array([2, 3])

In [12]:
x[-1]

9

The optional third parameter indicates the increment value:

In [13]:
x[0:8:2]

array([0, 2, 4, 6])

In [14]:
x[4:2:-1]

array([4, 3])

If you omit the start index, the slice implicitly starts from zero:

In [15]:
x[:4]

array([0, 1, 2, 3])

In [14]:
x[:999]

[0 1 2 3 4 5 6 7 8 9]


In [16]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Array Arithmetic

In [17]:
x = numpy.arange(5)
y = numpy.ones(5)
x+2*y

array([2., 3., 4., 5., 6.])

`dot` computes the dot product, or inner product, between arrays or matrices.

In [17]:
x = scipy.randn(5)
y = numpy.ones(5)
numpy.dot(x, y)

-4.36027379404


In [18]:
x = scipy.randn(5,3)
y = numpy.ones((3,2))
numpy.dot(x, y)

array([[-1.60796221, -1.60796221],
       [ 2.45072449,  2.45072449],
       [ 3.26153911,  3.26153911],
       [-0.02661148, -0.02661148],
       [-0.53308062, -0.53308062]])

## Boolean Operations

In [19]:
x = numpy.arange(10)
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [20]:
y = numpy.ones(10)
x < y

array([ True, False, False, False, False, False, False, False, False,
       False])

## Distance Metrics

In [22]:
from scipy.spatial import distance
distance.euclidean([0, 0], [3, 4])

5.0

In [23]:
distance.sqeuclidean([0, 0], [3, 4])

25.0

In [24]:
distance.cityblock([0, 0], [3, 4])

7

In [25]:
distance.chebyshev([0, 0], [3, 4])

4

The cosine distance measures the angle between two vectors:

In [27]:
distance.cosine([67, 0], [89, 0])

0.0

In [28]:
distance.cosine([67, 0], [0, 89])

1.0

## Sorting

NumPy arrays have a method, `sort`, which sorts the array *in-place*.

In [29]:
x = scipy.randn(5)
x

array([ 1.63687452, -0.03008817,  0.51252324,  0.19062929,  0.64571678])

In [30]:
x.sort()
x

array([-0.03008817,  0.19062929,  0.51252324,  0.64571678,  1.63687452])

`numpy.argsort` returns an array of indices, `ind`, such that `x[ind]` is a sorted version of `x`.

In [31]:
x = scipy.randn(5)
x

array([-1.05478044,  1.7730217 ,  0.98100478, -0.71488962,  0.4157945 ])

In [32]:
ind = numpy.argsort(x)
ind

array([0, 3, 4, 2, 1])

In [33]:
x[ind]

array([-1.05478044, -0.71488962,  0.4157945 ,  0.98100478,  1.7730217 ])

[&larr; Back to Index](index.html)